/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Front_end;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import login.model.Contato;
import login.model.TableModelContato;
import login.model.Usuario;

/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class Principal extends javax.swing.JFrame {
    protected TableModelContato tableModelContato;
    /**
     * Creates new form Principal
     *
     * @param nome
     * @throws java.sql.SQLException
     */
    private int id; 
    public Principal(String id) throws SQLException {
        this.id = Integer.parseInt(id);
        this.tableModelContato = new TableModelContato();
        initComponents();
        setResizable(false);
        listar();
        /**
         * Evendo dos clickes na linha da tabela
         */
        this.table.addMouseListener(new MouseAdapter() {
            
            @Override
            public void mouseClicked(MouseEvent e){
                if(e.getClickCount() == 2){
                    //busca o id da linha selecionada, busca no banco o 
                    //System.out.println((int)tableModelContato.getValueAt(table.getSelectedRow(), 3));
                    ResultSet rs = contato.findOn((int)tableModelContato.getValueAt(table.getSelectedRow(), 3));
                    
                    Contato con = new Contato();
                    try {
                        rs.next();
                        con.setNome(rs.getString("nome"));
                        con.setTelefone(rs.getString("telefone"));
                        con.setDdd(rs.getString("ddd"));
                        con.setEmail(rs.getString("email"));
                        con.setEndereco(rs.getString("endereco"));
                        con.setId(rs.getInt("id"));
                        
                        Visualizar vis = new Visualizar(Principal.this, con);
                        vis.setVisible(true);
                        
                      
                    } catch (SQLException ex) {
                        Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
                    }
               }
            }
        }); 
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        account = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table);

        jButton1.setText("Novo Contato");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        account.setText("Minha Conta");
        account.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 721, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(account, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(account))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Janela_Cadastro jan = new Janela_Cadastro(this);
        Contato con = new Contato();
        jan.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void accountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountActionPerformed
        Usuario user = new Usuario();
        ResultSet rs = user.findOne(id);
        try {
            rs.next();
            
            user.setName(rs.getString("name"));
            user.setEmail(rs.getString("email"));
            user.setId(rs.getInt("id"));
            
            Edit_User edit = new Edit_User(Principal.this, user);
            edit.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_accountActionPerformed
   
   
    /**
     * Metodo que faz a inserção dos dados na tabela
     * @throws java.sql.SQLException
     */
    Contato contato = new Contato();
    public void listar() throws SQLException {
        this.table.setModel(tableModelContato);
        this.table.removeAll();
        ResultSet rs = this.contato.find(id);
        
        while (rs.next()) {
            Contato pCont = new Contato();
            pCont.setNome(rs.getString("nome"));
            pCont.setTelefone(rs.getString("telefone"));
            pCont.setEmail(rs.getString("email"));
            pCont.setId(rs.getInt("id"));
            this.tableModelContato.addContato(pCont);
            
        }
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton account;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
